export const productList = [
  {
    id: 1,
    description: "Leche",
    quantity: 1,
    price: 2.5,
    isPurchased: false,
  },
  {
    id: 2,
    description: "Pan",
    quantity: 2,
    price: 1.5,
    isPurchased: true,
  },
  {
    id: 3,
    description: "Huevos",
    quantity: 1,
    price: 3,
    isPurchased: false,
  },
  {
    id: 4,
    description: "Bananas",
    quantity: 5,
    price: 2,
    isPurchased: true,
  },
  {
    id: 5,
    description: "Pollo",
    quantity: 1,
    price: 5,
    isPurchased: false,
  },
  {
    id: 6,
    description: "Queso",
    quantity: 1,
    price: 4,
    isPurchased: false,
  },
  {
    id: 7,
    description: "Tomate",
    quantity: 3,
    price: 1.2,
    isPurchased: true,
  },
  {
    id: 8,
    description: "Fideos",
    quantity: 2,
    price: 1.8,
    isPurchased: false,
  },
  {
    id: 9,
    description: "Café",
    quantity: 1,
    price: 6,
    isPurchased: true,
  },
  {
    id: 10,
    description: "Pasta dental",
    quantity: 1,
    price: 2,
    isPurchased: false,
  },
];
